framework:
  default_locale: 'ru'
  translator:
    default_path: '%kernel.project_dir%/translations'
  secret: '%env(APP_SECRET)%'

  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax

  templating:
    engines: [ 'twig', 'php' ]

  #esi: true
  #fragments: true
  php_errors:
    log: true
