parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Controller\:
    resource: '../src/Controller/'
    tags: [ 'controller.service_arguments' ]

  app.form.registration:
    class: App\Form\RegistrationFormType
    tags:
      - { name: form.type }

  mailer:
    alias: fos_user.mailer.noop
    public: true

  sonata.user.admin.user:
    class: "%sonata.user.admin.user.class%"
    arguments: [ ~, "%sonata.user.admin.user.entity%", "%sonata.user.admin.user.controller%" ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "%sonata.user.admin.groupname%", label_catalogue: "%sonata.user.admin.label_catalogue%", label: "users", icon: "<i class=\"fa fa-user\"></i>", show_in_dashboard: false }
    calls:
      - [ setUserManager, [ "@fos_user.user_manager" ] ]
      - [ setTranslationDomain, [ "%sonata.user.admin.user.translation_domain%" ] ]

  sonata.user.admin.group:
    class: "%sonata.user.admin.group.class%"
    arguments: [ ~, "%sonata.user.admin.group.entity%", "%sonata.user.admin.group.controller%" ]
    tags:
      - { name: sonata.admin, manager_type: orm, group: "%sonata.user.admin.groupname%", label_catalogue: "%sonata.user.admin.label_catalogue%", label: "groups", show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [ "%sonata.user.admin.group.translation_domain%" ] ]

  admin.book:
    class: App\Admin\BookAdmin
    arguments: [ ~, App\Entity\Book, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: Book }
  admin.user:
    class: App\Admin\UserAdmin
    arguments: [ ~, App\Entity\User, ~ ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: User }
